# Generated by Django 4.2.2 on 2023-07-05 18:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='deleted',
        ),
        migrations.RemoveField(
            model_name='useraddress',
            name='deleted',
        ),
        migrations.RemoveField(
            model_name='usergender',
            name='deleted',
        ),
        migrations.RemoveField(
            model_name='usergenderchoice',
            name='deleted',
        ),
        migrations.RemoveField(
            model_name='userimage',
            name='deleted',
        ),
        migrations.RemoveField(
            model_name='userlogin',
            name='deleted',
        ),
    ]
