# Generated by Django 4.2.2 on 2023-08-03 18:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_username_validation_alter_user_display_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='username_validation',
        ),
    ]
