# Generated by Django 4.2.2 on 2023-08-04 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_userverifyemail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userverifyemail',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
