# Generated by Django 4.2.2 on 2023-08-05 16:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_alter_userverifyemail_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='userverifyemail',
            name='user',
            field=models.OneToOneField(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='verified_email', to=settings.AUTH_USER_MODEL),
        ),
    ]
