# Generated by Django 4.2.2 on 2023-09-04 19:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_userpaymentmethodbillingaddress'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userpaymentmethodbillingaddress',
            old_name='paymentMethod',
            new_name='payment_method',
        ),
    ]
