# Generated by Django 4.2.2 on 2023-07-26 02:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sliders', '0002_slider_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sliderimage',
            name='slider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='sliders.slider'),
        ),
    ]
