# Generated by Django 4.2.2 on 2023-07-07 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brands', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='brand',
            old_name='description',
            new_name='bio',
        ),
        migrations.AddField(
            model_name='brand',
            name='stripe_account_id',
            field=models.CharField(blank=True, default='', max_length=120, unique=True),
        ),
    ]
