# Generated by Django 4.2.2 on 2023-07-08 02:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('brands', '0002_rename_description_brand_bio_brand_stripe_account_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brandowner',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_brands', to=settings.AUTH_USER_MODEL),
        ),
    ]
