# Generated by Django 4.2.2 on 2023-07-08 03:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('brands', '0003_alter_brandowner_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='brand',
            name='user',
        ),
        migrations.AddField(
            model_name='brand',
            name='owners',
            field=models.ManyToManyField(related_name='brands', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='brandowner',
            name='brand',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ownerss', to='brands.brand'),
        ),
    ]
