# Generated by Django 4.2.2 on 2023-07-08 03:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('brands', '0004_remove_brand_user_brand_owners_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='brand',
            old_name='owners',
            new_name='owner',
        ),
    ]
