# Generated by Django 4.2.2 on 2023-07-08 15:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('brands', '0009_remove_brandowner_image_remove_brandowner_is_active_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brandfollower',
            name='follower',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followed_brands', to=settings.AUTH_USER_MODEL),
        ),
    ]
