# Generated by Django 4.2.2 on 2023-07-08 15:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('brands', '0010_alter_brandfollower_follower'),
    ]

    operations = [
        migrations.CreateModel(
            name='BrandRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated', models.DateTimeField(auto_now_add=True, null=True)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='brands.brand')),
                ('rater', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rated_brands', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
