# Generated by Django 4.2.2 on 2023-07-08 15:49

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('brands', '0011_brandrate'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BrandRate',
            new_name='BrandRating',
        ),
    ]
