# Generated by Django 4.2.2 on 2023-07-08 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brands', '0012_rename_brandrate_brandrating'),
    ]

    operations = [
        migrations.AddField(
            model_name='brandrating',
            name='rating',
            field=models.IntegerField(default=0),
        ),
    ]
