# Generated by Django 4.2.2 on 2023-07-09 20:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('brands', '0013_brandrating_rating'),
    ]

    operations = [
        migrations.RenameField(
            model_name='brandfollower',
            old_name='follower',
            new_name='user',
        ),
    ]
