# Generated by Django 4.2.2 on 2023-07-09 20:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('brands', '0014_rename_follower_brandfollower_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='brandrating',
            old_name='rater',
            new_name='user',
        ),
    ]
