# Generated by Django 4.2.2 on 2023-08-23 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brands', '0016_rename_owner_brandowner_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='bio',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='brand',
            name='name',
            field=models.CharField(max_length=30),
        ),
    ]
