# Generated by Django 4.2.2 on 2023-07-11 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subcategoryproductspecificationitemoption',
            name='subcategory_product_specification_item',
        ),
        migrations.RemoveField(
            model_name='category',
            name='deleted',
        ),
        migrations.RemoveField(
            model_name='categoryimage',
            name='deleted',
        ),
        migrations.RemoveField(
            model_name='categoryproductspecification',
            name='deleted',
        ),
        migrations.RemoveField(
            model_name='categoryproductspecificationitem',
            name='deleted',
        ),
        migrations.RemoveField(
            model_name='subcategory',
            name='deleted',
        ),
        migrations.RemoveField(
            model_name='subcategoryimage',
            name='deleted',
        ),
        migrations.RemoveField(
            model_name='subcategoryproductspecification',
            name='deleted',
        ),
        migrations.RemoveField(
            model_name='subcategoryproductspecificationitem',
            name='deleted',
        ),
        migrations.AddField(
            model_name='categoryproductspecificationitem',
            name='item',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='subcategoryproductspecificationitem',
            name='item',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.DeleteModel(
            name='CategoryProductSpecificationItemOption',
        ),
        migrations.DeleteModel(
            name='SubcategoryProductSpecificationItemOption',
        ),
    ]
