# Generated by Django 4.2.2 on 2023-07-11 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='isbn',
            field=models.CharField(blank=True, max_length=14, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='productreview',
            name='comment',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='productspecification',
            name='label',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='productvariantitemspecification',
            name='label',
            field=models.CharField(max_length=100),
        ),
    ]
