# Generated by Django 4.2.2 on 2023-07-11 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_product_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='productvariantitem',
            name='price',
            field=models.IntegerField(default=0),
        ),
    ]
