# Generated by Django 4.2.2 on 2023-07-12 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_remove_product_price_remove_productvariant_sku_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='stripe_product_id',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='productvariantitem',
            name='stripe_product_id',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
    ]
