# Generated by Django 4.2.2 on 2023-07-13 18:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0009_alter_product_quantity_alter_productvariantitem_sku'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productvariantitem',
            name='product_variant',
        ),
        migrations.RemoveField(
            model_name='productvariantitemimage',
            name='product_variant_item',
        ),
        migrations.RemoveField(
            model_name='productvariantitemprice',
            name='product_variant_item',
        ),
        migrations.RemoveField(
            model_name='productvariantitemspecification',
            name='product_variant_item',
        ),
        migrations.RemoveField(
            model_name='productwishlistitem',
            name='product',
        ),
        migrations.RemoveField(
            model_name='productwishlistitem',
            name='wish_list',
        ),
        migrations.AddField(
            model_name='product',
            name='group_id',
            field=models.CharField(blank=True, default='', max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='productwishlist',
            name='product',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='wish_list_items', to='products.product'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='productwishlist',
            name='user',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='wish_list', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='ProductVariant',
        ),
        migrations.DeleteModel(
            name='ProductVariantItem',
        ),
        migrations.DeleteModel(
            name='ProductVariantItemImage',
        ),
        migrations.DeleteModel(
            name='ProductVariantItemPrice',
        ),
        migrations.DeleteModel(
            name='ProductVariantItemSpecification',
        ),
        migrations.DeleteModel(
            name='ProductWishListItem',
        ),
    ]
