# Generated by Django 4.2.2 on 2023-07-13 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_remove_productvariantitem_product_variant_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='group_id',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
    ]
