# Generated by Django 4.0.4 on 2023-07-14 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_alter_product_group_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='title',
            field=models.CharField(max_length=80),
        ),
        migrations.AlterField(
            model_name='productspecification',
            name='label',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='productspecification',
            name='value',
            field=models.CharField(blank=True, default='', max_length=30, null=True),
        ),
    ]
