# Generated by Django 4.2.2 on 2023-07-16 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_alter_productspecification_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productprice',
            name='stripe_price_id',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
