# Generated by Django 4.2.2 on 2023-07-20 02:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0015_productimagelimit'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProductImageLimit',
        ),
    ]
