# Generated by Django 4.2.2 on 2023-09-28 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0020_productlisting_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productdimension',
            name='height',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='productdimension',
            name='length',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='productdimension',
            name='weight',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='productdimension',
            name='width',
            field=models.CharField(default='', max_length=20),
        ),
    ]
