# Generated by Django 4.2.2 on 2023-10-01 16:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0004_categoryproductspecificationitemoption'),
        ('products', '0021_alter_productdimension_height_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productlisting',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product_listings', to='categories.category'),
        ),
    ]
