# Generated by Django 4.2.2 on 2023-10-01 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0022_productlisting_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='productlisting',
            name='image',
            field=models.CharField(default='', max_length=200),
        ),
    ]
