# Generated by Django 4.2.2 on 2023-10-02 15:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0023_productlisting_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductListingBaseVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='listing_base_variant', to='products.product')),
                ('product_listing', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='base_variant', to='products.productlisting')),
            ],
        ),
    ]
