# Generated by Django 4.2.2 on 2023-10-02 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0024_productlistingbasevariant'),
    ]

    operations = [
        migrations.AddField(
            model_name='productlistingbasevariant',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='productlistingbasevariant',
            name='updated',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
