# Generated by Django 4.2.2 on 2023-10-08 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0025_productlistingbasevariant_created_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='variant_order',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
    ]
